### ISSUE TITLE
CRITs Server icon missing from the pallette!

### ISSUE THREAD

**Issue by advancedeng** [brianwarehime/mcrits#8]
I am running Maltego in Windows while I have a remote installation of CRITs. 
Looking at the pallete, under mcrtis, the CRITs Server icon is missing and I cannot use any transformation. Everything was done according to instructions.

**Comment by brianwarehime** [comment]
Thanks for posting about this, I've actually stopped maintaining the code for this, and the guys from CRITs are actually taking it over. It's now being hosted on the official CRITs repo: https://github.com/crits/mcrits

**Comment by advancedeng** [comment]
OK thanks a lot!
